name: BlazorUI
on:
  push:
    paths:
    - 'src/Client/Web/**'
jobs:
  build:
    name: Test successful build and Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
    #I handled execution with "find | grep | xarg", to allow later bulk operations, with reducing the regex limits
      run: |
       find src/Client/Web/ -name "*BlazorUI.csproj" -type f | grep -v 'Tests.csproj' | xargs -n 1 dotnet restore
    - name: Build
      run: |
       find src/Client/Web/ -name "*BlazorUI.csproj" -type f | grep -v 'Tests.csproj' | xargs -n 1 dotnet build --no-restore
    - name: Test
      run: |
       find src/Client/Web/ -name "*BlazorUI.Tests.csproj" -type f | grep 'Tests.csproj' | xargs -n 1 dotnet test --no-build --verbosity normal
